class Constants:
    WINDOW_WIDTH = 1600
    WINDOW_HEIGHT = 1200
    WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
    REGULAR_SPEED = 5
    FRAMERATE = 60
    FONT = None
    DEBUG_MODE = True
    VOLUME = 0.1
