facts = {
    1: "All “cows” are female. Males are called bulls or steer. Before having a calf for the very first time, a female is called heifer. Then, once she has her first calf, she becomes a cow.",
    2: "There are over 800 different cattle breeds recognized worldwide (according to Wikipedia). For example, beef breeds are raised for their meat, and dairy breeds are raised to produce milk. At Clover Meadows Beef, we raise Angus-based cattle, which is a beef breed.",
    3: "Cows can see almost 360 degrees. As a result of this near-panoramic view, they can watch for predators from all angles. However, they don’t see well straight in front of them and they will typically turn their head to look at you.",
    4: "Cows have an acute sense of smell and can detect odors up to six miles away.",
    5: "Cows are very social and don’t like to be alone. For example, when a cow isolates herself it’s usually because she is sick or about to give birth.",
    6: "Cows have no upper front teeth. Therefore, when they’re eating food, they press their sharp bottom teeth against the top hard palate of their mouth to cut blades of grass.}",
    7: "A cow has 32 teeth, and will chew about 40-50 times a minute.",
    8: "A cow will chew for up to eight hours a day, and can move their jaws about 40,000 times a day.",
    9: "Since grass isn’t available in the winter for cattle to eat, it’s very important that farmers harvest grass so that cattle can eat it in the winter.",
    10: "Cows spend about 10 hours a day lying down.",
    11: "Cows will stand up and lay down about fourteen times a day.",
    12: "Cows can sleep while they’re standing.",
    13: "The first cow arrived in the U.S. in 1611 in Jamestown.",
    14: "There are approximately 98 million cows in the U.S.",
    15: "Cows are ruminants, which are cud chewing mammals. Other ruminant animals are sheep, giraffe, goats, and deer, just to name a few.",
    16: "The main stomach of a cow, the rumen, holds up to 50 gallons of food that has been partially digested. To put that in perspective, a bathtub can usually hold 30-50 gallons of water.",
    17: "A cow will consume about 40 pounds of food in a day.",
    18: "Cows can see color. They can even see red. When you see a Matador waving a red flag at a bull, the bull charges because of the flag’s movement.",
    19: "The average body temperature of a cow is 102 degrees Fahrenheit (38.8 Celsius)",
    20: "In the winter, cows thick skin and hair is a natural insulator that protects them from the bitter cold.",
    21: "Cows have 4 digestive compartments in one stomach – the rumen (this is where the cud comes from); the reticulum; omasum; and abomasum (this is sort of like a human’s stomach)."}
